### ISSUE TITLE
Prohibit import

### ISSUE THREAD

**Issue by arb** [continuationlabs/belly-button#15]
Thoughts on making `import` blocked?

**Comment by cjihrig** [comment]
Why? And is there an available rule for this?

**Comment by arb** [comment]
Because I don't like it. Just use `require`.

**Comment by cjihrig** [comment]
If there is an existing rule for it, I'm open to it. If the ES6 module system ever really takes off, it would be easy to turn the rule off again.

**Comment by cjihrig** [comment]
I don't think such a rule exists.
