### ISSUE TITLE
Update space-before-function-paren

### ISSUE THREAD

**Issue by cjihrig** [continuationlabs/belly-button#17]
Consider changing to `{"anonymous": "always", "named": "never"}`. This would allow `function foo()`, while still requiring `function ()` (anonymous vs. named). @arb thoughts?

**Comment by arb** [comment]
Not clear that this change would do? Sorry, I'm not an ESLint master.

**Comment by cjihrig** [comment]
Currently, you have to do this:

```javascript
function () {...}
function foo () {...}
```

With the proposed change (and what just went into the hapi config):

```javascript
function () {...}
function foo() {...}
```

Anonymous functions are the same. Named functions would no longer require the space between `foo` and `()`.

**Comment by arb** [comment]
Oh. No. I like the first one.
